# Generated by Django 5.2.9 on 2025-12-16 18:15

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cache_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('query_type', models.CharField(max_length=50)),
                ('sql_query', models.TextField()),
                ('result_data', models.JSONField()),
                ('row_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('last_accessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hit_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-last_accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_type', models.CharField(max_length=50)),
                ('endpoint', models.CharField(max_length=255)),
                ('sql_query', models.TextField()),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('bytes_processed', models.BigIntegerField(default=0)),
                ('bytes_billed', models.BigIntegerField(default=0)),
                ('row_count', models.IntegerField(default=0)),
                ('is_success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('cache_hit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
