# Generated by Django 5.2.9 on 2025-12-16 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacheentry',
            name='bigquery_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cache_entries', to='tables.bigquerytable'),
        ),
        migrations.AddField(
            model_name='querylog',
            name='bigquery_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query_logs', to='tables.bigquerytable'),
        ),
        migrations.AddIndex(
            model_name='cacheentry',
            index=models.Index(fields=['cache_key'], name='audit_cache_cache_k_074042_idx'),
        ),
        migrations.AddIndex(
            model_name='cacheentry',
            index=models.Index(fields=['expires_at'], name='audit_cache_expires_5e64e1_idx'),
        ),
        migrations.AddIndex(
            model_name='cacheentry',
            index=models.Index(fields=['bigquery_table', 'query_type'], name='audit_cache_bigquer_0ffb2e_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['-created_at'], name='audit_query_created_ff6358_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['query_type'], name='audit_query_query_t_c7c74f_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['bigquery_table', '-created_at'], name='audit_query_bigquer_79c578_idx'),
        ),
    ]
