# Generated by Django 5.2.9 on 2025-12-16 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
        ('tables', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['user', '-created_at'], name='audit_query_user_id_47ca51_idx'),
        ),
    ]
