# Generated by Django 5.2.9 on 2025-12-16 18:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GCPCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('credential_type', models.CharField(choices=[('service_account', 'Service Account'), ('oauth', 'OAuth')], default='service_account', max_length=20)),
                ('encrypted_credentials', models.BinaryField()),
                ('project_id', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gcp_credentials',
            },
        ),
    ]
