# Generated by Django 5.2.9 on 2025-12-16 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gcpcredential',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gcp_credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='gcpcredential',
            index=models.Index(fields=['user'], name='gcp_credent_user_id_da4c62_idx'),
        ),
        migrations.AddIndex(
            model_name='gcpcredential',
            index=models.Index(fields=['organization'], name='gcp_credent_organiz_cf7f80_idx'),
        ),
    ]
