# Generated by Django 5.2.9 on 2025-12-16 18:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rollup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rollup_id', models.CharField(max_length=100)),
                ('rollup_project', models.CharField(blank=True, max_length=255)),
                ('rollup_dataset', models.CharField(blank=True, max_length=255)),
                ('rollup_table', models.CharField(max_length=255)),
                ('dimensions', models.JSONField(default=list)),
                ('metrics', models.JSONField(default=list)),
                ('is_searchable', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('creating', 'Creating'), ('ready', 'Ready'), ('refreshing', 'Refreshing'), ('error', 'Error'), ('stale', 'Stale')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('row_count', models.BigIntegerField(default=0)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('last_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_duration_seconds', models.IntegerField(default=0)),
                ('min_date', models.DateField(blank=True, null=True)),
                ('max_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RollupConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_project', models.CharField(blank=True, max_length=255)),
                ('default_dataset', models.CharField(blank=True, max_length=255)),
                ('auto_refresh_enabled', models.BooleanField(default=False)),
                ('refresh_schedule_cron', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
