# Generated by Django 5.2.9 on 2025-12-16 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rollups', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollup',
            name='bigquery_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollups', to='tables.bigquerytable'),
        ),
        migrations.AddField(
            model_name='rollupconfig',
            name='bigquery_table',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rollup_config', to='tables.bigquerytable'),
        ),
        migrations.AddIndex(
            model_name='rollup',
            index=models.Index(fields=['bigquery_table', 'status'], name='rollups_rol_bigquer_90fc9f_idx'),
        ),
        migrations.AddIndex(
            model_name='rollup',
            index=models.Index(fields=['rollup_id'], name='rollups_rol_rollup__cccc3f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rollup',
            unique_together={('bigquery_table', 'rollup_id')},
        ),
    ]
