# Generated by Django 5.2.9 on 2025-12-16 18:15

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedDimension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimension_id', models.CharField(help_text='Unique identifier (e.g., "rec_id", "search_category")', max_length=100)),
                ('display_name', models.CharField(help_text='Human-readable name for UI', max_length=255)),
                ('sql_expression', models.TextField(help_text='SQL expression with {column} references')),
                ('depends_on', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Column names referenced in the expression', size=None)),
                ('data_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('FLOAT', 'Float'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean')], default='STRING', max_length=20)),
                ('is_filterable', models.BooleanField(default=True)),
                ('is_groupable', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=999)),
                ('filter_type', models.CharField(choices=[('single', 'Single Select'), ('multi', 'Multi Select'), ('range', 'Range'), ('date_range', 'Date Range'), ('boolean', 'Boolean')], default='multi', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calculated_dimensions',
                'ordering': ['sort_order', 'dimension_id'],
            },
        ),
        migrations.CreateModel(
            name='CalculatedMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_id', models.CharField(help_text='Unique identifier (e.g., "ctr", "conversion_rate")', max_length=100)),
                ('display_name', models.CharField(help_text='Human-readable name for UI', max_length=255)),
                ('formula', models.TextField(help_text='Formula expression (e.g., "{queries_pdp} / {queries}")')),
                ('sql_expression', models.TextField(help_text='Compiled SQL expression (e.g., "SAFE_DIVIDE(SUM(queries_pdp), SUM(queries))")')),
                ('depends_on', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='All metric IDs used in formula', size=None)),
                ('depends_on_base', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Base metric IDs used (deprecated - kept for compatibility)', size=None)),
                ('depends_on_calculated', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Calculated metric IDs used in formula', size=None)),
                ('depends_on_dimensions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Dimension IDs used in formula SQL expression', size=None)),
                ('format_type', models.CharField(choices=[('number', 'Number'), ('currency', 'Currency'), ('percent', 'Percent')], default='number', max_length=20)),
                ('decimal_places', models.IntegerField(default=2)),
                ('category', models.CharField(default='other', help_text='Metric category (volume, conversion, revenue, etc.)', max_length=50)),
                ('is_visible_by_default', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=999)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calculated_metrics',
                'ordering': ['sort_order', 'metric_id'],
            },
        ),
        migrations.CreateModel(
            name='CustomDimension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('dimension_type', models.CharField(choices=[('date_range', 'Date Range'), ('metric_condition', 'Metric Condition')], default='date_range', max_length=50)),
                ('metric', models.CharField(blank=True, help_text='Metric name to evaluate (for metric_condition type)', max_length=100, null=True)),
                ('values_json', models.JSONField(default=list, help_text='List of value definitions (date ranges or metric conditions)')),
            ],
            options={
                'db_table': 'custom_dimensions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimension_id', models.CharField(help_text='Unique identifier (e.g., "country", "channel")', max_length=100)),
                ('column_name', models.CharField(help_text='Actual BigQuery column name', max_length=255)),
                ('display_name', models.CharField(help_text='Human-readable name for UI', max_length=255)),
                ('data_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('FLOAT', 'Float'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean')], default='STRING', max_length=20)),
                ('is_filterable', models.BooleanField(default=True, help_text='Can be used in filters')),
                ('is_groupable', models.BooleanField(default=True, help_text='Can be used for GROUP BY')),
                ('sort_order', models.IntegerField(default=999)),
                ('filter_type', models.CharField(blank=True, choices=[('single', 'Single Select'), ('multi', 'Multi Select'), ('range', 'Range'), ('date_range', 'Date Range'), ('boolean', 'Boolean')], help_text='Type of filter UI to show', max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dimensions',
                'ordering': ['sort_order', 'dimension_id'],
            },
        ),
        migrations.CreateModel(
            name='SchemaConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_sort_metric', models.CharField(blank=True, help_text='Default metric ID to sort pivot tables by', max_length=100, null=True)),
                ('avg_per_day_metric', models.CharField(blank=True, help_text='Metric ID to use for average per day calculation', max_length=100, null=True)),
                ('pagination_threshold', models.IntegerField(default=100, help_text='Paginate dimension values when count exceeds this')),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Schema Configuration',
                'verbose_name_plural': 'Schema Configurations',
                'db_table': 'schema_configs',
            },
        ),
    ]
