# Generated by Django 5.2.9 on 2025-12-16 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schemas', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemaconfig',
            name='bigquery_table',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schema_config', to='tables.bigquerytable'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='schema_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='schemas.schemaconfig'),
        ),
        migrations.AddField(
            model_name='customdimension',
            name='schema_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_dimensions', to='schemas.schemaconfig'),
        ),
        migrations.AddField(
            model_name='calculatedmetric',
            name='schema_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_metrics', to='schemas.schemaconfig'),
        ),
        migrations.AddField(
            model_name='calculateddimension',
            name='schema_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_dimensions', to='schemas.schemaconfig'),
        ),
        migrations.AddIndex(
            model_name='dimension',
            index=models.Index(fields=['schema_config', 'dimension_id'], name='dimensions_schema__439b16_idx'),
        ),
        migrations.AddIndex(
            model_name='dimension',
            index=models.Index(fields=['is_filterable'], name='dimensions_is_filt_df27d6_idx'),
        ),
        migrations.AddIndex(
            model_name='dimension',
            index=models.Index(fields=['is_groupable'], name='dimensions_is_grou_15c74c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dimension',
            unique_together={('schema_config', 'dimension_id')},
        ),
        migrations.AlterUniqueTogether(
            name='customdimension',
            unique_together={('schema_config', 'name')},
        ),
        migrations.AddIndex(
            model_name='calculatedmetric',
            index=models.Index(fields=['schema_config', 'metric_id'], name='calculated__schema__2a2619_idx'),
        ),
        migrations.AddIndex(
            model_name='calculatedmetric',
            index=models.Index(fields=['category'], name='calculated__categor_a4e751_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calculatedmetric',
            unique_together={('schema_config', 'metric_id')},
        ),
        migrations.AddIndex(
            model_name='calculateddimension',
            index=models.Index(fields=['schema_config', 'dimension_id'], name='calculated__schema__3c5e63_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calculateddimension',
            unique_together={('schema_config', 'dimension_id')},
        ),
    ]
