# Generated by Django 5.2.9 on 2025-12-16 21:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_initial'),
        ('tables', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizedSourceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_table_path', models.CharField(help_text='Full BigQuery path to source table (project.dataset.table)', max_length=500)),
                ('optimized_table_name', models.CharField(help_text='Name of the optimized table (without project.dataset)', max_length=255)),
                ('target_project', models.CharField(blank=True, help_text='Target project for optimized table (defaults to source project)', max_length=255, null=True)),
                ('target_dataset', models.CharField(blank=True, help_text='Target dataset for optimized table (defaults to source dataset)', max_length=255, null=True)),
                ('composite_key_mappings', models.JSONField(default=list, help_text='List of composite key mappings: [{key_column_name, source_columns, metric_ids}]')),
                ('clustering', models.JSONField(blank=True, help_text='Clustering config: {columns: [], auto_detected: bool}', null=True)),
                ('partition_column', models.CharField(default='date', help_text='Column to partition by', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20)),
                ('last_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('last_refresh_error', models.TextField(blank=True, null=True)),
                ('row_count', models.BigIntegerField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('bigquery_table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='optimized_source_config', to='tables.bigquerytable')),
            ],
            options={
                'verbose_name': 'Optimized Source Configuration',
                'verbose_name_plural': 'Optimized Source Configurations',
                'db_table': 'optimized_source_configs',
            },
        ),
    ]
