# Generated by Django 5.2.9 on 2026-01-05 22:10

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_add_optimized_source_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdimension',
            name='source_metric',
            field=models.CharField(blank=True, help_text='Metric ID to use for bucketing (e.g., "queries", "revenue")', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customdimension',
            name='dimension_type',
            field=models.CharField(choices=[('date_range', 'Date Range'), ('metric_condition', 'Metric Condition'), ('metric_bucket', 'Metric Bucket')], default='date_range', max_length=50),
        ),
        migrations.AlterField(
            model_name='customdimension',
            name='metric',
            field=models.CharField(blank=True, help_text='Deprecated: Use source_metric instead', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customdimension',
            name='values_json',
            field=models.JSONField(default=list, help_text='List of value definitions (date ranges, metric conditions, or buckets)'),
        ),
        migrations.CreateModel(
            name='CustomMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('metric_id', models.CharField(help_text='Unique identifier for this custom metric', max_length=100)),
                ('source_metric', models.CharField(help_text='Metric ID to re-aggregate (e.g., "queries", "revenue")', max_length=100)),
                ('aggregation_type', models.CharField(choices=[('sum', 'Sum'), ('avg', 'Average'), ('max', 'Maximum'), ('min', 'Minimum'), ('count', 'Count')], default='sum', help_text='How to aggregate the source metric', max_length=20)),
                ('exclude_dimensions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Dimensions to exclude when re-aggregating (e.g., ["date"] to sum across all dates)', size=None)),
                ('format_type', models.CharField(choices=[('number', 'Number'), ('currency', 'Currency'), ('percent', 'Percent')], default='number', max_length=20)),
                ('decimal_places', models.IntegerField(default=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('schema_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_metrics', to='schemas.schemaconfig')),
            ],
            options={
                'db_table': 'custom_metrics',
                'ordering': ['name'],
                'unique_together': {('schema_config', 'metric_id')},
            },
        ),
    ]
