# Generated by Django 5.2.9 on 2026-01-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0004_add_custom_metric_and_update_custom_dimension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommetric',
            name='aggregation_type',
            field=models.CharField(choices=[('sum', 'Sum'), ('avg', 'Average'), ('max', 'Maximum'), ('min', 'Minimum'), ('count', 'Count'), ('avg_per_day', 'Average Per Day')], default='sum', help_text='How to aggregate the source metric (avg_per_day divides total by days in date range)', max_length=20),
        ),
    ]
