# Generated by Django 5.2.9 on 2026-01-12 12:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0005_add_avg_per_day_aggregation'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinedDimensionSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name for this joined dimension source', max_length=255)),
                ('original_filename', models.CharField(help_text='Original uploaded filename', max_length=255)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel')], help_text='File type of the uploaded file', max_length=10)),
                ('join_key_column', models.CharField(help_text='Column name in uploaded file used as join key', max_length=100)),
                ('target_dimension_id', models.CharField(help_text='Dimension ID in schema to join against (e.g., seller_id)', max_length=100)),
                ('bq_project', models.CharField(help_text='BigQuery project for lookup table', max_length=255)),
                ('bq_dataset', models.CharField(help_text='BigQuery dataset for lookup table', max_length=255)),
                ('bq_table', models.CharField(help_text='BigQuery table name (e.g., _lookup_seller_attributes_abc123)', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('schema_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_dimension_sources', to='schemas.schemaconfig')),
            ],
            options={
                'db_table': 'joined_dimension_sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JoinedDimensionColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimension_id', models.CharField(help_text='Unique ID for this joined dimension (e.g., joined_international_seller)', max_length=100)),
                ('source_column_name', models.CharField(help_text='Column name in the uploaded file', max_length=100)),
                ('display_name', models.CharField(help_text='Human-readable display name', max_length=255)),
                ('data_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('FLOAT', 'Float'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean')], default='STRING', max_length=20)),
                ('is_filterable', models.BooleanField(default=True)),
                ('is_groupable', models.BooleanField(default=True)),
                ('filter_type', models.CharField(choices=[('single', 'Single Select'), ('multi', 'Multi Select'), ('range', 'Range'), ('date_range', 'Date Range'), ('boolean', 'Boolean')], default='multi', max_length=20)),
                ('sort_order', models.IntegerField(default=999)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='schemas.joineddimensionsource')),
            ],
            options={
                'db_table': 'joined_dimension_columns',
                'ordering': ['sort_order', 'display_name'],
                'unique_together': {('source', 'dimension_id')},
            },
        ),
    ]
