# Generated by Django 5.2.9 on 2025-12-16 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bigquerytable',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bigquery_tables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bigquerytable',
            index=models.Index(fields=['owner'], name='bigquery_ta_owner_i_30bc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='bigquerytable',
            index=models.Index(fields=['organization'], name='bigquery_ta_organiz_29c378_idx'),
        ),
    ]
